/**
 * cmsms_uisge-beatha
 * @version v1.0.0
 * @link https://github.com/UisgeBeatha436/cmsms_uisge-beatha
 * @author Gregor
 * @license GPL-3.0
 */
var dyscrollup={btnID:"dyscrollup-btn",option:{showafter:300,scrolldelay:500,position:"right",image:"",shape:"circle",width:32,height:32},extendSource:function(e,t){var o;for(o in t)!1===e.hasOwnProperty(o)&&(e[o]=t[o]);return e},init:function(e){var t=this;void 0!==e&&(t.option=t.extendSource(e,t.option)),t.createBtn(),t.onscroll(),t.onclick()},createBtn:function(){var e,t=this;switch((e=document.createElement("div")).setAttribute("id",t.btnID),document.body.appendChild(e),(e=document.getElementById(t.btnID)).style.zIndex=999999,e.style.position="fixed",e.style.cursor="pointer",e.style.display="none",e.style.bottom="32px",t.option.position){case"left":e.style.left="32px";break;case"right":e.style.right="32px"}0<t.option.image.length?e.style.background="url("+t.option.image+") center center no-repeat":(e.style.backgroundColor="rgba(0,0,0,1)",e.style.color="#fff",e.style.textAlign="center",e.style.fontSize="20px",e.innerHTML="&#8593;",e.style.userSelect="none",e.style.msUserSelect="none",e.style.webkitUserSelect="none"),"circle"===t.option.shape&&(e.style.borderRadius="50%"),e.style.width=t.option.width+"px",e.style.height=t.option.height+"px",document.body.scrollTop>t.option.showafter||document.documentElement.scrollTop>t.option.showafter?e.style.display="block":e.style.display="none"},onscroll:function(){var e=this,t=document.getElementById(e.btnID),o=document.getElementById("header_logo"),n=document.querySelector("#navbarHeader");window.onscroll=function(){document.body.scrollTop>e.option.showafter||document.documentElement.scrollTop>e.option.showafter?("none"===t.style.display&&e.fadeIn(t),o.className="smallLogo",t.classList.contains("dyscrollup-btn-scrolling")||(t.classList.remove("click-locked"),n.classList.remove("navbar-transparent"),n.classList.add("bg-gradient"))):("none"!==t.style.display&&e.fadeOut(t),t.classList.remove("click-locked"),o.className="largeLogo",n.classList.remove("bg-gradient"),n.classList.add("navbar-transparent"))}},onclick:function(){var t=this,o=document.getElementById(t.btnID);o.addEventListener("click",function(e){return e.preventDefault(),o.classList.contains("click-locked")||(t.animate(),o.classList.add("click-locked")),!1})},fadeIn:function(e){e.style.display="block"},fadeOut:function(e){e.style.display="none"},animate:function(){var e=this,t=document.getElementById(e.btnID),o=document.body.scrollTop||document.documentElement.scrollTop,n=e.option.scrolldelay/50,l=Number(o*n/e.option.scrolldelay);n<1&&(n=1,l=o);var s=setInterval(function(){t.classList.add("dyscrollup-btn-scrolling"),o-=l,document.body.scrollTop=o,(document.documentElement.scrollTop=o)<=0&&(clearInterval(s),t.classList.remove("dyscrollup-btn-scrolling"))},n)}};
//# sourceMappingURL=dyscrollup.js.map
